name: Main

on:
  push:
    branches: [main]

  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  Main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fetch XML
        run: curl https://decrypt.co/feed -o news.xml

      - name: Convert to JSON
        run: npx convert-xml-to-json ./news.xml ./news.json

      - uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - id: deployment
        uses: actions/deploy-pages@v1